development:
  host: "<%= ENV.fetch("MYSQL_HOST") %>"
  database: "<%= ENV.fetch("MYSQL_DATABASE") %>"
  username: "<%= ENV.fetch("MYSQL_USER") %>"
  password: "<%= ENV.fetch("MYSQL_PASSWORD") %>"
production:
  host: "<%= ENV.fetch("MYSQL_HOST") %>"
  database: "<%= ENV.fetch("MYSQL_DATABASE") %>"
  username: "<%= ENV.fetch("MYSQL_USER") %>"
  password: "<%= ENV.fetch("MYSQL_PASSWORD") %>"


